import Link from "next/link";
import { ArrowRight, Boxes, CheckCircle2, Database, Gauge, HardDrive, ShieldCheck, Store, Users } from "lucide-react";
import { CtaBand } from "@/components/marketing/cta-band";
import { ProductDemo } from "@/components/marketing/product-demo";
import { PlanCards } from "@/components/pricing/plan-cards";
import { cloudService, productCapabilities } from "@/config/commercial";
import { tutorials } from "@/config/tutorials";
import { siteConfig } from "@/config/site";

const capabilityIcons = [Gauge, Boxes, Store, Users, ShieldCheck, Database];
const flow = ["Elige tu licencia", "Envía tu solicitud", "Realiza la transferencia", "Verificamos el pago", "Recibe licencia e instalador", "Activa Blue Cat"];

export default function HomePage() {
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"SoftwareApplication",name:"Blue Cat",applicationCategory:"BusinessApplication",operatingSystem:"Windows",description:siteConfig.description,offers:{"@type":"Offer",priceSpecification:{"@type":"PriceSpecification",description:"Cotización personalizada"}}}).replace(/</g,"\\u003c")}}/>
    <section className="hero"><div className="container hero-content"><span className="eyebrow">ERP + POS instalable</span><h1 className="display">Tu operación cerca.<br/>Tu negocio bajo control.</h1><p className="lede">Blue Cat conecta ventas, caja, inventario y clientes en una aplicación local pensada para responder rápido en el lugar donde trabajas.</p><div className="hero-actions"><Link className="button button-primary" href="/comprar">Solicitar una licencia <ArrowRight size={18}/></Link><Link className="button button-secondary" href="/producto">Explorar el producto</Link></div><div className="hero-note"><span><CheckCircle2 size={15}/> Licencia perpetua</span><span><CheckCircle2 size={15}/> 12 meses de actualizaciones</span><span><CheckCircle2 size={15}/> Cloud opcional</span></div><ProductDemo/></div></section>
    <section className="logo-strip"><div className="container trust-grid"><div className="trust-item"><HardDrive size={21}/> Operación local</div><div className="trust-item"><ShieldCheck size={21}/> Acceso por roles</div><div className="trust-item"><Store size={21}/> Preparado para crecer</div><div className="trust-item"><Database size={21}/> Nube solo si la necesitas</div></div></section>
    <section className="section"><div className="container"><span className="eyebrow">Una sola operación</span><h2 className="headline">Del mostrador al inventario, sin perder el hilo.</h2><p className="lede">Presentamos únicamente capacidades verificadas en el producto actual. Las configuraciones especiales se evalúan antes de comprometerlas.</p><div className="grid-3" style={{ marginTop: "2rem" }}>{productCapabilities.slice(0,6).map((item,index) => { const Icon=capabilityIcons[index]; return <article className="card" key={item.name}><span className="card-icon"><Icon size={21}/></span><h3>{item.name}</h3><p>{item.description}</p><span className={`status ${item.availability === "configuration" ? "config" : item.availability === "custom" ? "custom" : ""}`}>{item.availability === "available" ? "Disponible" : item.availability === "configuration" ? "Según configuración" : "Evaluación personalizada"}</span></article>; })}</div><div style={{ marginTop: "1.4rem" }}><Link className="button button-secondary" href="/modulos">Ver todos los módulos <ArrowRight size={17}/></Link></div></div></section>
    <section className="section dark-section"><div className="container"><span className="eyebrow" style={{ color: "var(--cyan)" }}>Compra acompañada</span><h2 className="headline">De la elección a la activación, con trazabilidad.</h2><p className="lede">La transferencia se revisa manualmente antes de emitir una licencia o habilitar una descarga.</p><div className="steps">{flow.map((step) => <div className="step" key={step}><strong>{step}</strong></div>)}</div></div></section>
    <section className="section"><div className="container"><span className="eyebrow">Licencias</span><h2 className="headline">Pago único para el software.<br/>Servicios recurrentes solo cuando aportan valor.</h2><p className="lede">Ambas licencias permiten conservar y usar la última versión obtenida. El derecho a nuevas actualizaciones dura 12 meses y luego puede renovarse.</p><PlanCards/><div className="cloud-callout"><div><span className="plan-label" style={{ color: "#7ee7f5" }}>Servicio mensual opcional</span><h3>{cloudService.name}</h3><p>{cloudService.description}</p></div><Link className="button button-ghost" href="/cloud-sync">Conocer Cloud Sync</Link></div></div></section>
    <section className="section" style={{ background: "white" }}><div className="container"><span className="eyebrow">Aprende en la web</span><h2 className="headline">Tutoriales breves que muestran el flujo.</h2><div className="grid-3" style={{ marginTop: "2rem" }}>{tutorials.map((tutorial) => <article className="card" key={tutorial.slug}><span className="plan-label">{tutorial.category} · {tutorial.estimatedMinutes} min</span><h3 style={{ marginTop: ".8rem" }}>{tutorial.title}</h3><p>{tutorial.description}</p><Link className="button button-secondary" style={{ marginTop: "1.3rem" }} href={`/tutoriales/${tutorial.slug}`}>Iniciar tutorial</Link></article>)}</div></div></section>
    <CtaBand/>
  </>;
}
