-- Phase 1: align the reproducible CRM schema with the API already in production.
-- Every change is conditional so migrated installations keep their existing data.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS cliente_direccion (
  id_direccion INT NOT NULL AUTO_INCREMENT,
  id_cliente INT NOT NULL,
  tipo VARCHAR(30) DEFAULT 'facturacion',
  direccion VARCHAR(255) DEFAULT NULL,
  ciudad VARCHAR(100) DEFAULT NULL,
  comuna VARCHAR(100) DEFAULT NULL,
  principal TINYINT(1) DEFAULT 0,
  PRIMARY KEY (id_direccion),
  KEY idx_cliente_direccion_cliente (id_cliente),
  CONSTRAINT fk_cliente_direccion_cliente FOREIGN KEY (id_cliente)
    REFERENCES cliente(id_cliente) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='comuna')=0,'ALTER TABLE cliente ADD COLUMN comuna VARCHAR(100) NULL AFTER ciudad','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='tipo')=0,"ALTER TABLE cliente ADD COLUMN tipo VARCHAR(20) NULL DEFAULT 'empresa' AFTER codigo",'DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='clasificacion')=0,'ALTER TABLE cliente ADD COLUMN clasificacion VARCHAR(50) NULL AFTER categoria','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='origen')=0,'ALTER TABLE cliente ADD COLUMN origen VARCHAR(50) NULL AFTER clasificacion','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='id_vendedor')=0,'ALTER TABLE cliente ADD COLUMN id_vendedor INT NULL AFTER origen','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='lista_precios')=0,'ALTER TABLE cliente ADD COLUMN lista_precios VARCHAR(30) NULL AFTER id_vendedor','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='moneda')=0,"ALTER TABLE cliente ADD COLUMN moneda VARCHAR(10) NULL DEFAULT 'CLP' AFTER lista_precios",'DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='canal')=0,'ALTER TABLE cliente ADD COLUMN canal VARCHAR(30) NULL AFTER moneda','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='activo')=0,'ALTER TABLE cliente ADD COLUMN activo TINYINT(1) NULL DEFAULT 1 AFTER estado','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente' AND COLUMN_NAME='updated_at')=0,'ALTER TABLE cliente ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER fecha_creacion','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;

SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_contacto' AND COLUMN_NAME='apellido')=0,'ALTER TABLE cliente_contacto ADD COLUMN apellido VARCHAR(100) NULL AFTER nombre','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_contacto' AND COLUMN_NAME='whatsapp')=0,'ALTER TABLE cliente_contacto ADD COLUMN whatsapp VARCHAR(30) NULL AFTER telefono','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;

SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='limite_credito')=0,'ALTER TABLE cliente_credito ADD COLUMN limite_credito DECIMAL(12,2) NULL DEFAULT 0 AFTER id_cliente','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='credito_utilizado')=0,'ALTER TABLE cliente_credito ADD COLUMN credito_utilizado DECIMAL(12,2) NULL DEFAULT 0 AFTER limite_credito','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='dias_credito')=0,'ALTER TABLE cliente_credito ADD COLUMN dias_credito INT NULL DEFAULT 0 AFTER credito_utilizado','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='condiciones_pago')=0,'ALTER TABLE cliente_credito ADD COLUMN condiciones_pago VARCHAR(100) NULL AFTER dias_credito','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='bloqueado')=0,'ALTER TABLE cliente_credito ADD COLUMN bloqueado TINYINT(1) NULL DEFAULT 0 AFTER condiciones_pago','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='created_at')=0,'ALTER TABLE cliente_credito ADD COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='updated_at')=0,'ALTER TABLE cliente_credito ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='id_user' AND IS_NULLABLE='NO')=1,'ALTER TABLE cliente_credito MODIFY id_user INT NULL','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='monto' AND IS_NULLABLE='NO')=1,'ALTER TABLE cliente_credito MODIFY monto DECIMAL(12,2) NULL','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_credito' AND COLUMN_NAME='fecha_otorgamiento' AND IS_NULLABLE='NO')=1,'ALTER TABLE cliente_credito MODIFY fecha_otorgamiento DATE NULL','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;

SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_actividad' AND COLUMN_NAME='asunto')=0,'ALTER TABLE cliente_actividad ADD COLUMN asunto VARCHAR(200) NULL AFTER tipo','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_actividad' AND COLUMN_NAME='fecha_planificada')=0,'ALTER TABLE cliente_actividad ADD COLUMN fecha_planificada DATETIME NULL AFTER descripcion','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_actividad' AND COLUMN_NAME='fecha_realizada')=0,'ALTER TABLE cliente_actividad ADD COLUMN fecha_realizada DATETIME NULL AFTER fecha_planificada','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_actividad' AND COLUMN_NAME='estado')=0,"ALTER TABLE cliente_actividad ADD COLUMN estado VARCHAR(20) NULL DEFAULT 'pendiente' AFTER fecha_realizada",'DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_actividad' AND COLUMN_NAME='created_at')=0,'ALTER TABLE cliente_actividad ADD COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_actividad' AND COLUMN_NAME='updated_at')=0,'ALTER TABLE cliente_actividad ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;

SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_etiqueta_rel' AND COLUMN_NAME='id_rel')=0,'ALTER TABLE cliente_etiqueta_rel ADD COLUMN id_rel INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;

SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_auditoria' AND COLUMN_NAME='entidad')=0,"ALTER TABLE cliente_auditoria ADD COLUMN entidad VARCHAR(50) NOT NULL DEFAULT 'cliente' AFTER accion",'DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_auditoria' AND COLUMN_NAME='id_entidad')=0,'ALTER TABLE cliente_auditoria ADD COLUMN id_entidad INT NULL AFTER entidad','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_auditoria' AND COLUMN_NAME='valor_anterior')=0,'ALTER TABLE cliente_auditoria ADD COLUMN valor_anterior JSON NULL AFTER id_entidad','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_auditoria' AND COLUMN_NAME='valor_nuevo')=0,'ALTER TABLE cliente_auditoria ADD COLUMN valor_nuevo JSON NULL AFTER valor_anterior','DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cliente_auditoria' AND COLUMN_NAME='nivel')=0,"ALTER TABLE cliente_auditoria ADD COLUMN nivel VARCHAR(20) NULL DEFAULT 'INFO' AFTER ip",'DO 0'); PREPARE phase1_stmt FROM @ddl; EXECUTE phase1_stmt; DEALLOCATE PREPARE phase1_stmt;
