-- Módulo Facturación - Blue-Cat ERP

CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` int NOT NULL AUTO_INCREMENT,
  `id_user` int NOT NULL,
  `rut` varchar(20) DEFAULT NULL,
  `razon_social` varchar(200) NOT NULL,
  `nombre` varchar(100) DEFAULT NULL,
  `direccion` varchar(255) DEFAULT NULL,
  `ciudad` varchar(100) DEFAULT NULL,
  `comuna` varchar(100) DEFAULT NULL,
  `correo` varchar(100) DEFAULT NULL,
  `telefono` varchar(30) DEFAULT NULL,
  `giro` varchar(200) DEFAULT NULL,
  `fecha_creacion` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cliente`),
  KEY `id_user` (`id_user`),
  CONSTRAINT `cliente_ibfk_1` FOREIGN KEY (`id_user`) REFERENCES `usuario` (`id_user`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `factura` (
  `id_factura` int NOT NULL AUTO_INCREMENT,
  `id_user` int NOT NULL,
  `id_sesion` int DEFAULT NULL,
  `id_pedido` int DEFAULT NULL,
  `id_cliente` int DEFAULT NULL,
  `folio` int DEFAULT NULL,
  `numero` varchar(50) DEFAULT NULL,
  `tipo` enum('FACTURA','BOLETA','NOTA_CREDITO','NOTA_DEBITO','GUIA') DEFAULT 'FACTURA',
  `estado` enum('BORRADOR','PENDIENTE','EMITIDA','ACEPTADA','PAGADA','PARCIAL','VENCIDA','ANULADA','RECHAZADA') DEFAULT 'BORRADOR',
  `fecha_emision` datetime DEFAULT NULL,
  `fecha_vencimiento` date DEFAULT NULL,
  `subtotal` int NOT NULL DEFAULT '0',
  `descuento` int NOT NULL DEFAULT '0',
  `exento` int NOT NULL DEFAULT '0',
  `neto` int NOT NULL DEFAULT '0',
  `iva` int NOT NULL DEFAULT '0',
  `total` int NOT NULL DEFAULT '0',
  `pagado` int NOT NULL DEFAULT '0',
  `saldo` int NOT NULL DEFAULT '0',
  `metodo_pago` varchar(50) DEFAULT NULL,
  `sucursal` varchar(100) DEFAULT NULL,
  `vendedor` varchar(100) DEFAULT NULL,
  `observaciones` text,
  `orden_compra` varchar(100) DEFAULT NULL,
  `track_id` varchar(50) DEFAULT NULL,
  `respuesta_sii` text,
  `fecha_envio_sii` datetime DEFAULT NULL,
  `fecha_aceptacion_sii` datetime DEFAULT NULL,
  `fecha_creacion` datetime DEFAULT CURRENT_TIMESTAMP,
  `fecha_modificacion` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_factura`),
  KEY `id_user` (`id_user`),
  KEY `id_sesion` (`id_sesion`),
  KEY `id_pedido` (`id_pedido`),
  KEY `id_cliente` (`id_cliente`),
  KEY `estado` (`estado`),
  KEY `folio` (`folio`),
  CONSTRAINT `factura_ibfk_1` FOREIGN KEY (`id_user`) REFERENCES `usuario` (`id_user`) ON DELETE RESTRICT,
  CONSTRAINT `factura_ibfk_2` FOREIGN KEY (`id_sesion`) REFERENCES `sesion` (`id_sesion`) ON DELETE SET NULL,
  CONSTRAINT `factura_ibfk_3` FOREIGN KEY (`id_pedido`) REFERENCES `pedido` (`id_pedido`) ON DELETE SET NULL,
  CONSTRAINT `factura_ibfk_4` FOREIGN KEY (`id_cliente`) REFERENCES `cliente` (`id_cliente`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `factura_detalle` (
  `id_detalle` int NOT NULL AUTO_INCREMENT,
  `id_factura` int NOT NULL,
  `id_producto` int DEFAULT NULL,
  `sku` varchar(50) DEFAULT NULL,
  `codigo` varchar(50) DEFAULT NULL,
  `producto` varchar(200) NOT NULL,
  `descripcion` varchar(500) DEFAULT NULL,
  `cantidad` int NOT NULL DEFAULT '1',
  `unidad` varchar(20) DEFAULT 'UN',
  `precio` int NOT NULL DEFAULT '0',
  `descuento` int NOT NULL DEFAULT '0',
  `neto` int NOT NULL DEFAULT '0',
  `iva` int NOT NULL DEFAULT '0',
  `total` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_detalle`),
  KEY `id_factura` (`id_factura`),
  KEY `id_producto` (`id_producto`),
  CONSTRAINT `factura_detalle_ibfk_1` FOREIGN KEY (`id_factura`) REFERENCES `factura` (`id_factura`) ON DELETE CASCADE,
  CONSTRAINT `factura_detalle_ibfk_2` FOREIGN KEY (`id_producto`) REFERENCES `producto` (`id_producto`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `factura_pago` (
  `id_pago` int NOT NULL AUTO_INCREMENT,
  `id_factura` int NOT NULL,
  `metodo` varchar(50) NOT NULL,
  `monto` int NOT NULL,
  `fecha` datetime DEFAULT CURRENT_TIMESTAMP,
  `banco` varchar(100) DEFAULT NULL,
  `referencia` varchar(100) DEFAULT NULL,
  `comprobante` varchar(255) DEFAULT NULL,
  `observacion` text,
  PRIMARY KEY (`id_pago`),
  KEY `id_factura` (`id_factura`),
  CONSTRAINT `factura_pago_ibfk_1` FOREIGN KEY (`id_factura`) REFERENCES `factura` (`id_factura`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `factura_historial` (
  `id_historial` int NOT NULL AUTO_INCREMENT,
  `id_factura` int NOT NULL,
  `id_user` int DEFAULT NULL,
  `accion` varchar(100) NOT NULL,
  `valor_anterior` text,
  `valor_nuevo` text,
  `ip` varchar(45) DEFAULT NULL,
  `fecha` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_historial`),
  KEY `id_factura` (`id_factura`),
  KEY `id_user` (`id_user`),
  CONSTRAINT `factura_historial_ibfk_1` FOREIGN KEY (`id_factura`) REFERENCES `factura` (`id_factura`) ON DELETE CASCADE,
  CONSTRAINT `factura_historial_ibfk_2` FOREIGN KEY (`id_user`) REFERENCES `usuario` (`id_user`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
