-- Módulo Proveedores - Blue-Cat ERP

CREATE TABLE IF NOT EXISTS `proveedor` (
  `id_proveedor` int NOT NULL AUTO_INCREMENT,
  `id_user` int NOT NULL,
  `codigo` varchar(30) DEFAULT NULL,
  `rut` varchar(20) DEFAULT NULL,
  `razon_social` varchar(250) NOT NULL,
  `nombre_comercial` varchar(250) DEFAULT NULL,
  `giro` varchar(200) DEFAULT NULL,
  `categoria` varchar(100) DEFAULT NULL,
  `tipo` enum('NACIONAL','EXTRANJERO') DEFAULT 'NACIONAL',
  `estado` enum('ACTIVO','INACTIVO','SUSPENDIDO','BLOQUEADO','PENDIENTE') DEFAULT 'ACTIVO',
  `pais` varchar(100) DEFAULT 'Chile',
  `region` varchar(100) DEFAULT NULL,
  `ciudad` varchar(100) DEFAULT NULL,
  `comuna` varchar(100) DEFAULT NULL,
  `direccion` varchar(255) DEFAULT NULL,
  `codigo_postal` varchar(20) DEFAULT NULL,
  `telefono` varchar(30) DEFAULT NULL,
  `correo` varchar(100) DEFAULT NULL,
  `sitio_web` varchar(255) DEFAULT NULL,
  `contacto_principal` varchar(100) DEFAULT NULL,
  `responsable_interno` varchar(100) DEFAULT NULL,
  `condicion_pago` varchar(100) DEFAULT NULL,
  `limite_credito` int DEFAULT '0',
  `moneda` varchar(10) DEFAULT 'CLP',
  `descuento` int DEFAULT '0',
  `tiempo_entrega` int DEFAULT NULL,
  `pedido_minimo` int DEFAULT '0',
  `incoterm` varchar(50) DEFAULT NULL,
  `tipo_contribuyente` varchar(100) DEFAULT NULL,
  `exento_iva` tinyint(1) DEFAULT '0',
  `retefuente` tinyint(1) DEFAULT '0',
  `actividad_economica` varchar(100) DEFAULT NULL,
  `resolucion_sii` varchar(100) DEFAULT NULL,
  `notas` text,
  `fecha_creacion` datetime DEFAULT CURRENT_TIMESTAMP,
  `fecha_modificacion` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_proveedor`),
  KEY `id_user` (`id_user`),
  KEY `rut` (`rut`),
  KEY `estado` (`estado`),
  CONSTRAINT `proveedor_ibfk_1` FOREIGN KEY (`id_user`) REFERENCES `usuario` (`id_user`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `proveedor_contacto` (
  `id_contacto` int NOT NULL AUTO_INCREMENT,
  `id_proveedor` int NOT NULL,
  `nombre` varchar(150) NOT NULL,
  `cargo` varchar(100) DEFAULT NULL,
  `departamento` varchar(100) DEFAULT NULL,
  `correo` varchar(100) DEFAULT NULL,
  `telefono` varchar(30) DEFAULT NULL,
  `celular` varchar(30) DEFAULT NULL,
  `whatsapp` varchar(30) DEFAULT NULL,
  `principal` tinyint(1) DEFAULT '0',
  `notas` text,
  PRIMARY KEY (`id_contacto`),
  KEY `id_proveedor` (`id_proveedor`),
  CONSTRAINT `proveedor_contacto_ibfk_1` FOREIGN KEY (`id_proveedor`) REFERENCES `proveedor` (`id_proveedor`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `proveedor_banco` (
  `id_banco` int NOT NULL AUTO_INCREMENT,
  `id_proveedor` int NOT NULL,
  `banco` varchar(100) NOT NULL,
  `tipo_cuenta` varchar(50) DEFAULT NULL,
  `numero_cuenta` varchar(50) DEFAULT NULL,
  `titular` varchar(150) DEFAULT NULL,
  `rut_titular` varchar(20) DEFAULT NULL,
  `swift` varchar(20) DEFAULT NULL,
  `iban` varchar(50) DEFAULT NULL,
  `correo_pagos` varchar(100) DEFAULT NULL,
  `principal` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id_banco`),
  KEY `id_proveedor` (`id_proveedor`),
  CONSTRAINT `proveedor_banco_ibfk_1` FOREIGN KEY (`id_proveedor`) REFERENCES `proveedor` (`id_proveedor`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `proveedor_producto` (
  `id_prov_producto` int NOT NULL AUTO_INCREMENT,
  `id_proveedor` int NOT NULL,
  `id_producto` int DEFAULT NULL,
  `sku_proveedor` varchar(50) DEFAULT NULL,
  `sku_interno` varchar(50) DEFAULT NULL,
  `producto` varchar(200) NOT NULL,
  `marca` varchar(100) DEFAULT NULL,
  `categoria` varchar(100) DEFAULT NULL,
  `precio_compra` int DEFAULT '0',
  `ultimo_precio` int DEFAULT '0',
  `costo_promedio` int DEFAULT '0',
  `moneda` varchar(10) DEFAULT 'CLP',
  `tiempo_entrega` int DEFAULT NULL,
  `pedido_minimo` int DEFAULT '0',
  `estado` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  PRIMARY KEY (`id_prov_producto`),
  KEY `id_proveedor` (`id_proveedor`),
  KEY `id_producto` (`id_producto`),
  CONSTRAINT `proveedor_producto_ibfk_1` FOREIGN KEY (`id_proveedor`) REFERENCES `proveedor` (`id_proveedor`) ON DELETE CASCADE,
  CONSTRAINT `proveedor_producto_ibfk_2` FOREIGN KEY (`id_producto`) REFERENCES `producto` (`id_producto`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `proveedor_historial` (
  `id_historial` int NOT NULL AUTO_INCREMENT,
  `id_proveedor` int NOT NULL,
  `id_user` int DEFAULT NULL,
  `accion` varchar(100) NOT NULL,
  `valor_anterior` text,
  `valor_nuevo` text,
  `ip` varchar(45) DEFAULT NULL,
  `fecha` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_historial`),
  KEY `id_proveedor` (`id_proveedor`),
  CONSTRAINT `proveedor_historial_ibfk_1` FOREIGN KEY (`id_proveedor`) REFERENCES `proveedor` (`id_proveedor`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
